// SQLodin Discussions (SOD) Registry
// Automatically updated by `sqlodin sod promote <slug>`

#let sod-documents = (
  (
    number: "0001",
    slug: "sod-process",
    title: "The SQLodin Discussion Process",
    state: "committed",
    area: "process",
    category: "Process Memo",
    status: "Committed",
    created: "2026-09-22",
    updated: "2026-09-25",
    summary: "Defines the SOD lifecycle, design-discussion structure, revision rules and Typst workflow.",
    source: "docs/sod/records/0001-sod-process.typ",
    pdf: "sod-0001-sod-process.pdf",
  ),
  (
    number: "0002",
    slug: "sqlodin-architecture",
    title: "SQLodin Architecture: Multi-Master Replicated SQLite Protocol",
    state: "committed",
    area: "architecture",
    category: "Architectural Specification",
    status: "Committed",
    created: "2026-09-22",
    updated: "2026-09-25",
    summary: "Accepted fixed-voter architecture: whole upstream library, durable SQL ordering, explicit read semantics and bounded clients.",
    source: "docs/sod/records/0002-sqlodin-architecture.typ",
    pdf: "sod-0002-sqlodin-architecture.pdf",
  ),
  (
    number: "0003",
    slug: "mathematical-foundations-and-proofs",
    title: "Mathematical Foundations and Safety Proofs for Multi-Master Consensus",
    state: "committed",
    area: "theory",
    category: "Formal Specification & Theory",
    status: "Committed",
    created: "2026-09-22",
    updated: "2026-09-25",
    summary: "Agreement and host composition arguments, bounded model checks, selected inductive proofs and their explicit assumptions.",
    source: "docs/sod/records/0003-mathematical-foundations-and-proofs.typ",
    pdf: "sod-0003-mathematical-foundations-and-proofs.pdf",
  ),
  (
    number: "0004",
    slug: "production-sql-and-durable-throughput",
    title: "Production SQL and Durable Throughput",
    state: "committed",
    area: "storage",
    category: "Architecture and Implementation Plan",
    status: "Committed",
    created: "2026-09-22",
    updated: "2026-09-25",
    summary: "Accepted durable host design and tradeoffs; fixed-voter correctness qualification completed with performance shortfalls disclosed.",
    source: "docs/sod/records/0004-production-sql-and-durable-throughput.typ",
    pdf: "sod-0004-production-sql-and-durable-throughput.pdf",
  ),
)
